name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
 
    - name: Build Docker Image
      run: docker build -t wuxyyin/wsc-screentocode-service -f ./backend/Dockerfile ./backend
 
    - name: Push Docker Image
      run: docker push wuxyyin/wsc-screentocode-service
